In [3]:
# Basic Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')


from sklearn.model_selection import train_test_split, RandomizedSearchCV

# Evaluation Metrics for Binary Classification
from sklearn.metrics import (
    accuracy_score, 
    precision_score, 
    recall_score, 
    f1_score, 
    roc_auc_score, 
    confusion_matrix, 
    roc_curve
)

# Models
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier
%pip install catboost lightgbm
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier

Collecting catboost
  Using cached catboost-1.2.10-cp311-cp311-win_amd64.whl.metadata (1.5 kB)
Collecting lightgbm
  Using cached lightgbm-4.7.0-py3-none-win_amd64.whl.metadata (18 kB)
Collecting graphviz (from catboost)
  Using cached graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: matplotlib in d:\ml-krish naik\vehicle-insurance-pred\.venv\lib\site-packages (from catboost) (3.11.2)
Requirement already satisfied: numpy<3.0,>=1.16.0 in d:\ml-krish naik\vehicle-insurance-pred\.venv\lib\site-packages (from catboost) (2.4.6)
Requirement already satisfied: pandas<4.0,>=0.24 in d:\ml-krish naik\vehicle-insurance-pred\.venv\lib\site-packages (from catboost) (3.0.6)
Requirement already satisfied: scipy in d:\ml-krish naik\vehicle-insurance-pred\.venv\lib\site-packages (from catboost) (1.17.1)
Collecting plotly (from catboost)
  Downloading plotly-7.1.0-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: six in d:\ml-krish naik\vehicle-insurance-pred\.venv\lib\site-packages (from catboost) (1.17.0)
Requirement already satisfied: narwhals>=1.15 in d:\ml-krish naik\vehicle-insurance-pred\.venv\lib\site-packages (from lightgbm) (2.26.0)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\ml-krish naik\vehicle-insurance-pred\.venv\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\ml-krish naik\vehicle-insurance-pred\.venv\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2026.4)
Requirement already satisfied: contourpy>=1.0.1 in d:\ml-krish naik\vehicle-insurance-pred\.venv\lib\site-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in d:\ml-krish naik\vehicle-insurance-pred\.venv\lib\site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in d:\ml-krish naik\vehicle-insurance-pred\.venv\lib\site-packages (from matplotlib->catboost) (4.65.0)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\ml-krish naik\vehicle-insurance-pred\.venv\lib\site-packages (from matplotlib->catboost) (1.5.1)
Requirement already satisfied: packaging>=20.0 in d:\ml-krish naik\vehicle-insurance-pred\.venv\lib\site-packages (from matplotlib->catboost) (26.3)
Requirement already satisfied: pillow>=9 in d:\ml-krish naik\vehicle-insurance-pred\.venv\lib\site-packages (from matplotlib->catboost) (12.3.0)
Requirement already satisfied: pyparsing>=3 in d:\ml-krish naik\vehicle-insurance-pred\.venv\lib\site-packages (from matplotlib->catboost) (3.3.3)
Using cached catboost-1.2.10-cp311-cp311-win_amd64.whl (100.2 MB)
Using cached lightgbm-4.7.0-py3-none-win_amd64.whl (1.4 MB)
Using cached graphviz-0.21-py3-none-any.whl (47 kB)
Downloading plotly-7.1.0-py3-none-any.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.1/9.7 MB 656.4 kB/s eta 0:00:15
    --------------------------------------- 0.1/9.7 MB 901.1 kB/s eta 0:00:11
    --------------------------------------- 0.2/9.7 MB 1.2 MB/s eta 0:00:09
   - -------------------------------------- 0.3/9.7 MB 1.2 MB/s eta 0:00:08
   - -------------------------------------- 0.3/9.7 MB 1.2 MB/s eta 0:00:08
   - -------------------------------------- 0.4/9.7 MB 1.2 MB/s eta 0:00:08
   - -------------------------------------- 0.5/9.7 MB 1.3 MB/s eta 0:00:08
   -- ------------------------------------- 0.6/9.7 MB 1.4 MB/s eta 0:00:07
   -- ------------------------------------- 0.6/9.7 MB 1.4 MB/s eta 0:00:07
   --- ------------------------------------ 0.7/9.7 MB 1.5 MB/s eta 0:00:07
   --- ------------------------------------ 0.9/9.7 MB 1.6 MB/s eta 0:00:06
   ---- ----------------------------------- 1.0/9.7 MB 1.6 MB/s eta 0:00:06
   ---- ----------------------------------- 1.0/9.7 MB 1.6 MB/s eta 0:00:06
   ---- ----------------------------------- 1.2/9.7 MB 1.7 MB/s eta 0:00:06
   ----- ---------------------------------- 1.3/9.7 MB 1.7 MB/s eta 0:00:05
   ----- ---------------------------------- 1.4/9.7 MB 1.8 MB/s eta 0:00:05
   ------ --------------------------------- 1.5/9.7 MB 1.8 MB/s eta 0:00:05
   ------ --------------------------------- 1.6/9.7 MB 1.8 MB/s eta 0:00:05
   ------- -------------------------------- 1.8/9.7 MB 1.9 MB/s eta 0:00:05
   -------- ------------------------------- 1.9/9.7 MB 2.0 MB/s eta 0:00:04
   -------- ------------------------------- 2.1/9.7 MB 2.1 MB/s eta 0:00:04
   --------- ------------------------------ 2.3/9.7 MB 2.1 MB/s eta 0:00:04
   ---------- ----------------------------- 2.4/9.7 MB 2.2 MB/s eta 0:00:04
   ----------- ---------------------------- 2.7/9.7 MB 2.3 MB/s eta 0:00:04
   ----------- ---------------------------- 2.9/9.7 MB 2.4 MB/s eta 0:00:03
   ------------ --------------------------- 3.1/9.7 MB 2.4 MB/s eta 0:00:03
   ------------- -------------------------- 3.3/9.7 MB 2.5 MB/s eta 0:00:03
   -------------- ------------------------- 3.5/9.7 MB 2.6 MB/s eta 0:00:03
   --------------- ------------------------ 3.8/9.7 MB 2.7 MB/s eta 0:00:03
   ---------------- ----------------------- 4.0/9.7 MB 2.8 MB/s eta 0:00:03
   ----------------- ---------------------- 4.2/9.7 MB 2.9 MB/s eta 0:00:02
   ------------------ --------------------- 4.6/9.7 MB 3.0 MB/s eta 0:00:02
   ------------------- -------------------- 4.8/9.7 MB 3.0 MB/s eta 0:00:02
   -------------------- ------------------- 5.0/9.7 MB 3.1 MB/s eta 0:00:02
   ---------------------- ----------------- 5.4/9.7 MB 3.3 MB/s eta 0:00:02
   ----------------------- ---------------- 5.7/9.7 MB 3.3 MB/s eta 0:00:02
   ------------------------ --------------- 6.1/9.7 MB 3.4 MB/s eta 0:00:02
   -------------------------- ------------- 6.5/9.7 MB 3.6 MB/s eta 0:00:01
   ---------------------------- ----------- 6.9/9.7 MB 3.7 MB/s eta 0:00:01
   ------------------------------ --------- 7.4/9.7 MB 3.9 MB/s eta 0:00:01
   -------------------------------- ------- 7.8/9.7 MB 4.0 MB/s eta 0:00:01
   --------------------------------- ------ 8.2/9.7 MB 4.1 MB/s eta 0:00:01
   ----------------------------------- ---- 8.6/9.7 MB 4.2 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.7 MB 4.5 MB/s eta 0:00:01
   ---------------------------------------  9.6/9.7 MB 4.5 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.7 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 4.4 MB/s eta 0:00:00
Installing collected packages: plotly, graphviz, lightgbm, catboost
Successfully installed catboost-1.2.10 graphviz-0.21 lightgbm-4.7.0 plotly-7.1.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
# Load dataset
df = pd.read_csv('raw.csv')

# Drop identifier if present
if 'id' in df.columns:
    df = df.drop(columns=['id'])

# Show Top 5 Records
df.head()

,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,Male,44,1,28.0,0,> 2 Years,Yes,40454.0,26.0,217,1
1,Male,76,1,3.0,0,1-2 Year,No,33536.0,26.0,183,0
2,Male,47,1,28.0,0,> 2 Years,Yes,38294.0,26.0,27,1
3,Male,21,1,11.0,1,< 1 Year,No,28619.0,152.0,203,0
4,Female,29,1,41.0,1,< 1 Year,No,27496.0,152.0,39,0

In [8]:
# Preparing X and y variables (Target is 'Response')
X = df.drop(columns=['Response'])
y = df['Response']

# Preprocessing & Selection
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split, RandomizedSearchCV
# Identify column types
num_features = X.select_dtypes(exclude="object").columns.tolist()
cat_features = X.select_dtypes(include="object").columns.tolist()

# Preprocessing Pipeline
numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder(drop='first', handle_unknown='ignore')

preprocessor = ColumnTransformer(
    transformers=[
        ("OneHotEncoder", oh_transformer, cat_features),
        ("StandardScaler", numeric_transformer, num_features)
    ]
)

# Fit-transform features
X = preprocessor.fit_transform(X)

# Split dataset into train and test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
print("X_train shape:", X_train.shape, "| X_test shape:", X_test.shape)

X_train shape: (304887, 11) | X_test shape: (76222, 11)

In [9]:
X

array([[ 1.        ,  0.        ,  1.        , ...,  0.57453868,
        -1.58723371,  0.74879538],
       [ 1.        ,  0.        ,  0.        , ...,  0.17263624,
        -1.58723371,  0.34244286],
       [ 1.        ,  0.        ,  1.        , ...,  0.4490531 ,
        -1.58723371, -1.52199808],
       ...,
       [ 1.        ,  1.        ,  0.        , ...,  0.26454281,
         0.88491205,  0.07950888],
       [ 0.        ,  0.        ,  1.        , ...,  0.81638891,
         0.22075349, -0.96027549],
       [ 1.        ,  0.        ,  0.        , ...,  0.6513986 ,
        -1.58723371,  0.98782627]], shape=(381109, 11))

In [10]:
def evaluate_model(true, predicted, predicted_proba):
    accuracy = accuracy_score(true, predicted)
    f1 = f1_score(true, predicted, average='binary', zero_division=0)
    precision = precision_score(true, predicted, average='binary', zero_division=0)
    recall = recall_score(true, predicted, average='binary', zero_division=0)
    roc_auc = roc_auc_score(true, predicted_proba)
    return accuracy, f1, precision, recall, roc_auc

In [11]:
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1),
    "AdaBoost": AdaBoostClassifier(random_state=42),
    "XGBoost": XGBClassifier(eval_metric='logloss', random_state=42),
    "CatBoost": CatBoostClassifier(verbose=False, random_state=42),
    "LightGBM": LGBMClassifier(random_state=42)
}

model_list = []
roc_auc_list = []

for name, model in models.items():
    model.fit(X_train, y_train)
    
    # Predictions
    y_train_pred = model.predict(X_train)
    y_train_proba = model.predict_proba(X_train)[:, 1]
    
    y_test_pred = model.predict(X_test)
    y_test_proba = model.predict_proba(X_test)[:, 1]
    
    # Evaluate
    train_acc, train_f1, train_prec, train_rec, train_auc = evaluate_model(y_train, y_train_pred, y_train_proba)
    test_acc, test_f1, test_prec, test_rec, test_auc = evaluate_model(y_test, y_test_pred, y_test_proba)
    
    model_list.append(name)
    roc_auc_list.append(test_auc)
    
    print(name)
    print('Model performance for Training set')
    print("- Accuracy: {:.4f}".format(train_acc))
    print("- ROC-AUC: {:.4f}".format(train_auc))
    print("- F1 Score: {:.4f}".format(train_f1))
    print('----------------------------------')
    print('Model performance for Test set')
    print("- Accuracy: {:.4f}".format(test_acc))
    print("- ROC-AUC: {:.4f}".format(test_auc))
    print("- F1 Score: {:.4f}".format(test_f1))
    print('=' * 35)
    print('\n')

# Display Model Comparison Table
results_df = pd.DataFrame(list(zip(model_list, roc_auc_list)), columns=['Model Name', 'ROC_AUC_Score'])
results_df = results_df.sort_values(by="ROC_AUC_Score", ascending=False).reset_index(drop=True)
results_df

Logistic Regression
Model performance for Training set
- Accuracy: 0.8774
- ROC-AUC: 0.8363
- F1 Score: 0.0003
----------------------------------
Model performance for Test set
- Accuracy: 0.8774
- ROC-AUC: 0.8385
- F1 Score: 0.0002
===================================


Decision Tree
Model performance for Training set
- Accuracy: 0.9999
- ROC-AUC: 1.0000
- F1 Score: 0.9996
----------------------------------
Model performance for Test set
- Accuracy: 0.8233
- ROC-AUC: 0.5990
- F1 Score: 0.2950
===================================


Random Forest
Model performance for Training set
- Accuracy: 0.9999
- ROC-AUC: 1.0000
- F1 Score: 0.9995
----------------------------------
Model performance for Test set
- Accuracy: 0.8670
- ROC-AUC: 0.8334
- F1 Score: 0.1832
===================================


AdaBoost
Model performance for Training set
- Accuracy: 0.8774
- ROC-AUC: 0.8450
- F1 Score: 0.0000
----------------------------------
Model performance for Test set
- Accuracy: 0.8774
- ROC-AUC: 0.8458
- F1 Score: 0.0000
===================================


XGBoost
Model performance for Training set
- Accuracy: 0.8813
- ROC-AUC: 0.8803
- F1 Score: 0.0960
----------------------------------
Model performance for Test set
- Accuracy: 0.8764
- ROC-AUC: 0.8556
- F1 Score: 0.0515
===================================


CatBoost
Model performance for Training set
- Accuracy: 0.8827
- ROC-AUC: 0.8817
- F1 Score: 0.1201
----------------------------------
Model performance for Test set
- Accuracy: 0.8763
- ROC-AUC: 0.8566
- F1 Score: 0.0613
===================================


[LightGBM] [Info] Number of positive: 37368, number of negative: 267519
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006578 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 737
[LightGBM] [Info] Number of data points in the train set: 304887, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.122563 -> initscore=-1.968376
[LightGBM] [Info] Start training from score -1.968376
LightGBM
Model performance for Training set
- Accuracy: 0.8776
- ROC-AUC: 0.8625
- F1 Score: 0.0113
----------------------------------
Model performance for Test set
- Accuracy: 0.8768
- ROC-AUC: 0.8570
- F1 Score: 0.0074
===================================

            Model Name  ROC_AUC_Score
0             LightGBM       0.856964
1             CatBoost       0.856613
2              XGBoost       0.855621
3             AdaBoost       0.845823
4  Logistic Regression       0.838516
5        Random Forest       0.833424
6        Decision Tree       0.599041

In [12]:
# Display Model Comparison Table
results_df = pd.DataFrame(list(zip(model_list, roc_auc_list)), columns=['Model Name', 'ROC_AUC_Score'])
results_df = results_df.sort_values(by="ROC_AUC_Score", ascending=False).reset_index(drop=True)
results_df

            Model Name  ROC_AUC_Score
0             LightGBM       0.856964
1             CatBoost       0.856613
2              XGBoost       0.855621
3             AdaBoost       0.845823
4  Logistic Regression       0.838516
5        Random Forest       0.833424
6        Decision Tree       0.599041

In [20]:
df['Vehicle_Damage']

0         Yes
1          No
2         Yes
3          No
4          No
         ...
381104     No
381105     No
381106     No
381107    Yes
381108     No
Name: Vehicle_Damage, Length: 381109, dtype: str